// teamMembers.ts
import { TeamMember } from "./types";

export const teamMembers: TeamMember[] = [
  {
    name: "OZZY OSMAN",
    image: "/images/team-1.png",
    title: "FOUNDER & GLOBAL CEO AT THE BRAVE AGENCY – NY, USA",
    roles: [
      "BRAND LEADERSHIP AT DIESEL USA – NY, USA",
      "BRAND LEADERSHIP AT BACCARAT – NY, USA",
      "BRAND LEADERSHIP AT DOLCE & GABBANA – NY, USA",
      "BRAND LEADERSHIP AT GUCCI GROUP – NY, USA",
      "FOUNDER & BRAND LEADERSHIP AT THE PRADA USA – NY, USA",
    ],
  },
  {
    name: "PATRICK VALEO",
    image: "/images/team-2.png",
    title: "CHIEF EXECUTIVE OFFICER AT THE BRAVE AGENCY – NY, USA",
    roles: [
      "MEMBER BOARD AT FASHION GROUP INTERNATIONAL – NY, USA",
      "CHIEF EXECUTIVE OFFICER AT DIESEL USA – NY, USA",
      "PRESIDENT AT MCM WORLDWIDE – NY, USA",
      "PRESIDENT AT SMCP – NY, USA",
      "VICE PRESIDENT AT DOLCE & GABBANA – NY, USA",
      "VICE PRESIDENT AT GUCCI GROUP – NY, USA",
    ],
  },
  {
    name: "JAQUI LIVIDINI",
    image: "/images/team-3.png",
    title: "CHIEF EXECUTION OFFICER AT THE BRAVE AGENCY – NY, USA",
    roles: [
      "FOUNDER & CEO AT LIVIDINI & COMPANY – NY, USA",
      "BRAND LEADERSHIP, SAKS FIFTH AVENUE – NY, USA",
      "VICE CHAIRMAN OF THE FIT BOARD OF TRUSTEES – NY, USA",
      "MEMBER BOARD AT FASHION GROUP INTERNATIONAL – NY, USA",
      "100 MOST INFLUENTIAL PEOPLE IN THE FASHION INDUSTRY",
    ],
  },
  {
    name: "DR. ALI IMTIAZ",
    image: "/images/team-4.png",
    title: "FOUNDER & CHIEF STRATEGY OFFICER AT THE BRAVE AGENCY – NY, USA",
    roles: [
      "CEO AT BIZTEC VENTURES – GERMANY",
      "PRINCIPAL AT RITZENHOEFER & CO – GERMANY",
      "LEAD COORDINATOR EUROPEAN PROJ AT FIR ACHEN – GERMANY",
      "MEMBER OF HARVARD BUSINESS SCHOOL GLOBAL NETWORK",
      "MEMBER & DIRECTOR OF HCP EXECUTIVE COMMITTEE 20-21",
    ],
  },
  {
    name: "MARYANNE GRISZ",
    image: "/images/team-5.png",
    title: "ADVISOR & CONSULTANT AT THE BRAVE AGENCY – NY, USA",
    roles: [
      "PRESIDENT & CEO AT THE FASHION GROUP INTERNATIONAL – NY, USA",
      "PARTNER & EXECUTIVE PRODUCER AT THE ONEROCK MOVINGPICTURES – NY, USA",
      "PRODUCER AT THE MARYANNE GRISZ LLC – NY, USA",
      "EXECUTIVE PRODUCER & DIRECTOR AT DRESSED – NY, USA",
    ],
  },
];
